POST http://{{keycloak-host}}/realms/app/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id = ext-client &
client_secret = 28l5hqqBmi84WUQTD4XX0ABLrMhsReQy &
grant_type = password &
username = vtramo15 &
password = ciao &
scope = openid
