POST http://{{keycloak-host}}/realms/quarkus/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id = dev-admin &
client_secret = MixA18JzVpzriRFyYg5Uj1RI3lg4qRZe &
grant_type = password &
username = vtramo250 &
password = ciao &
scope = openid
