apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-kc-data
  labels:
    app: keycloak
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: postgres-kc-data