apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-data
  labels:
    app: mongodb
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadOnlyMany
    - ReadWriteMany
  hostPath:
    path: /mongodb-data
    type: Directory